version: '3.7'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - ./scripts/aws:/etc/localstack/init/ready.d
  server:
    depends_on:
      - localstack
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_S3_BUCKET_NAME=mfu-202312
      - PORT=8080
